### ISSUE TITLE
jQueryを2重に読み込んでるのなぜですか

### ISSUE THREAD

**Issue by kmyk** [Koki-Yamaguchi/Koki-Yamaguchi.github.io#2]
https://github.com/Koki-Yamaguchi/Koki-Yamaguchi.github.io/blob/4831b21915c9412f34885be8fad05532fa149121/generator.py#L10-L11

試してはないんだけどこれどちらか一方だけで十分な気がする

**Comment by Koki-Yamaguchi** [comment]
上の方はもともと書いていたやつで、filter.jsが3.xで動かなかったため、下の方を書き足したという感じです

**Comment by kmyk** [comment]
filters.jsってもしかしてどこかからのコピペだったりしますか？
今後の拡張としては AtCoder Problems の返すjsonをjavascriptで受け取ってブラウザ上でtableを構築することになるはずなので、中身理解してちゃんと書き直した方がいいと思います

**Comment by Koki-Yamaguchi** [comment]
はい
間違いないと思います
