### ISSUE TITLE
Atcoder Beginner Contest が空なのなぜですか

### ISSUE THREAD

**Issue by kmyk** [Koki-Yamaguchi/Koki-Yamaguchi.github.io#3]
どうせ空欄ならそもそも書かない方がいいように思える

**Comment by Koki-Yamaguchi** [comment]
最初普通に実装したんですが、URLの仕様が面倒なことになっている（同じABCでもARCと同時に開催中されている場合とそうでない場合でURLが違う）ことにあとで気づいて、とりあえず放置しています。なんとかする予定です。

**Comment by kmyk** [comment]
あれか 面倒なのすごく分かる
問題ID (`agc001_a` みたいなやつ) は一意なのでこっちに寄せるとよいよ

**Comment by Koki-Yamaguchi** [comment]
できるかやってみます
