### ISSUE TITLE
絞り込み改良したくない？

### ISSUE THREAD

**Issue by kmyk** [Koki-Yamaguchi/Koki-Yamaguchi.github.io#4]
-    現状はラジオボタンだけどチェックボックスにしてほしさがある
-   「すべて」「グラフ」などのラベルをクリックしても認識してほしい

後者は Semantic-UI の https://semantic-ui.com/modules/checkbox.html#radio を見る限りだと動くはずなんだけど不思議 どこかが悪さしてそう
なお一般には `<label><input ...> hoge</label>` が正しい https://developer.mozilla.org/ja/docs/Web/HTML/Element/label#Examples

**Comment by Koki-Yamaguchi** [comment]
絞り込み、改良したさしかないんですが、現状完全にライブラリに頼っているのでまだ思い通りにできていない点と、データベースの管理が下手っぽい（タグをスペース区切られた一つのデータとしてもってる）という点が問題です

**Comment by kmyk** [comment]
>   タグをスペース区切られた一つのデータとしてもってる

教科書的にはすごくだめなのですが、今回の用途 (鯖側でタグの検索クエリを実行しない) からすると実装速度/実行速度の両方の点でこれで正解に見える (競プロの `REP` macro的な感じ)

**Comment by Koki-Yamaguchi** [comment]
なるほど...ではそこはとりあえずよいものとしておきます
チェックボックスは始めからそうしたいとは思っていたので、なんとかします
ラベルもクリックできた方がいいのはそれはそうですね
