### ISSUE TITLE
sys.stdoutへの代入はリダイレクトの方がいいと思う

### ISSUE THREAD

**Issue by kmyk** [Koki-Yamaguchi/Koki-Yamaguchi.github.io#5]
これ

https://github.com/Koki-Yamaguchi/Koki-Yamaguchi.github.io/blob/06f2ca64ebe4239fbbf2bbde4e6e4f5d08f611af/generator.py#L111-L120

普通に標準出力にprintして、呼び出すときに以下のようにするのが綺麗だし楽だと思う

``` sh
$ python generate.py > index.html
```

**Comment by Koki-Yamaguchi** [comment]
確かに
そのように修正します
