### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by kmyk** [Koki-Yamaguchi/Koki-Yamaguchi.github.io#6]
slackでも書いたやつ
今回は問題にならないのでこのままでいいんだけど、それが何かぐらいは理解しておきましょう

https://github.com/Koki-Yamaguchi/Koki-Yamaguchi.github.io/blob/06f2ca64ebe4239fbbf2bbde4e6e4f5d08f611af/generator.py#L90-L92

**Comment by kmyk** [comment]
閉じとくね

**Comment by Koki-Yamaguchi** [comment]
はい
